"""Lista ampliada de canales para monitoreo de YouTube.

Total: 650 canales únicos.
Base original del usuario: 176 canales.
Ampliación previa: 250 canales.
Nueva ampliación: 224 canales adicionales.

Objetivo: cubrir un espectro muy amplio de YouTube: streaming, gaming, música,
infantil/familiar, ciencia, educación, IA, tecnología, finanzas, noticias,
documentales, cultura pop, podcasts, comida, viajes, deportes y lifestyle.

Compatibilidad:
- Mantiene CHANNEL_URLS como una lista literal de strings.
- Los comentarios clasifican la lista original y las ampliaciones por categoría.
- El pipeline puede seguir haciendo: from channels import CHANNEL_URLS
"""

CHANNEL_URLS = [
    # ============================================================
    # ORIGINALES CLASIFICADOS
    # ============================================================
    # --- Finanzas, negocios y emprendimiento (34) ---
    'https://www.youtube.com/@MarianoTrejo',
    'https://www.youtube.com/@MisPropiasFinanzas',
    'https://www.youtube.com/@AdriàSolàPastor',
    'https://www.youtube.com/@EduardoRosas',
    'https://www.youtube.com/@CésarDabiánFinanzas',
    'https://www.youtube.com/@MorisDieck',
    'https://www.youtube.com/@AdrianSaenz',
    'https://www.youtube.com/@FinanzasparatodosYT',
    'https://www.youtube.com/@LuisMiNegocios',
    'https://www.youtube.com/@AprendizFinanciero',
    'https://www.youtube.com/@negociosyfinanzas2559',
    'https://www.youtube.com/@pequenocerdocapitalista',
    'https://www.youtube.com/@AlexHormozi',
    'https://www.youtube.com/@CalebHammer',
    'https://www.youtube.com/c/Myprimermillón',
    'https://www.youtube.com/@starterstory',
    'https://www.youtube.com/@irenealbacete',
    'https://www.youtube.com/@bulkin_uri',
    'https://www.youtube.com/@ExitoFinancieroOficial',
    'https://www.youtube.com/@compuestospodcast',
    'https://www.youtube.com/@JaimeHigueraEspanol',
    'https://www.youtube.com/@omareducacionfinanciera',
    'https://www.youtube.com/@gustavo-entrala',
    'https://www.youtube.com/@ricardoalcados',
    'https://www.youtube.com/@inversioninteligente_alain',
    'https://www.youtube.com/@TwoCentsPBS',
    'https://www.youtube.com/@bravosresearch',
    'https://www.youtube.com/@ThatNateBlack',
    'https://www.youtube.com/@comofuncionatunegocio',
    'https://www.youtube.com/@SantiagoAmatFinanzas',
    'https://www.youtube.com/@thefinancialfreedomgirl',
    'https://www.youtube.com/@bilinkis',
    'https://www.youtube.com/@EmprendeAprendiendo',
    'https://www.youtube.com/@TheDiaryOfACEO',

    # --- Tecnología, IA y programación (26) ---
    'https://www.youtube.com/@la_inteligencia_artificial',
    'https://www.youtube.com/@humphrey',
    'https://www.youtube.com/@jefillysh',
    'https://www.youtube.com/@EDteam',
    'https://www.youtube.com/@ProgramadorX',
    'https://www.youtube.com/@Platzi',
    'https://www.youtube.com/@NateGentile7',
    'https://www.youtube.com/@midulive',
    'https://www.youtube.com/@soydalto',
    'https://www.youtube.com/@vidaprogramador',
    'https://www.youtube.com/@DotDager',
    'https://www.youtube.com/@elrincondeldev',
    'https://www.youtube.com/@mourede',
    'https://www.youtube.com/@FaztTech',
    'https://www.youtube.com/@ELMAIKINIDEV',
    'https://www.youtube.com/@IA_Innova',
    'https://www.youtube.com/@WesRoth',
    'https://www.youtube.com/@RingaTech',
    'https://www.youtube.com/@alejavirivera',
    'https://www.youtube.com/@jomakaze',
    'https://www.youtube.com/@KenJee_ds',
    'https://www.youtube.com/@HolaMundoDev',
    'https://www.youtube.com/@CreaYTransforma',
    'https://www.youtube.com/@TinaHuang1',
    'https://www.youtube.com/@AI_In_Context',
    'https://www.youtube.com/@DotCSV',

    # --- Ciencia, educación y divulgación (44) ---
    'https://www.youtube.com/@doctorfision',
    'https://www.youtube.com/@EvaMariaBeristain',
    'https://www.youtube.com/@Unicoos',
    'https://www.youtube.com/@QuantumFracture',
    'https://www.youtube.com/@lagatadeschrodinger',
    'https://www.youtube.com/@CdeCiencia',
    'https://www.youtube.com/@elrobotdeplaton',
    'https://www.youtube.com/@PhysicsGirl',
    'https://www.youtube.com/@Veritasium',
    'https://www.youtube.com/@Vsauce',
    'https://www.youtube.com/@minutephysics',
    'https://www.youtube.com/@SmarterEveryDay',
    'https://www.youtube.com/@AsapSCIENCE',
    'https://www.youtube.com/@PBSSpaceTime',
    'https://www.youtube.com/@TheActionLab',
    'https://www.youtube.com/@numberphile',
    'https://www.youtube.com/@crashcourse',
    'https://www.youtube.com/@TwoMinutePapers',
    'https://www.youtube.com/@UnaFisicaSimplificada',
    'https://www.youtube.com/@watop_esp',
    'https://www.youtube.com/@ProfePiola',
    'https://www.youtube.com/@Sapienciapráctica',
    'https://www.youtube.com/@derivando',
    'https://www.youtube.com/@Antroporama',
    'https://www.youtube.com/@LaHiperactina',
    'https://www.youtube.com/@kurzgesagt',
    'https://www.youtube.com/@MarkRober',
    'https://www.youtube.com/@TomScott',
    'https://www.youtube.com/@RealEngineering',
    'https://www.youtube.com/@Wendoverproductions',
    'https://www.youtube.com/@cleoabram',
    'https://www.youtube.com/@StuffMadeHere',
    'https://www.youtube.com/@sabinehossenfelder',
    'https://www.youtube.com/@3blue1brown',
    'https://www.youtube.com/@standupmaths',
    'https://www.youtube.com/@PracticalEngineeringChannel',
    'https://www.youtube.com/@domainofscience',
    'https://www.youtube.com/@BranchEducation',
    'https://www.youtube.com/@upandatom',
    'https://www.youtube.com/@NileRed',
    'https://www.youtube.com/@ScienceAsylum',
    'https://www.youtube.com/@acollierastro',
    'https://www.youtube.com/@eons',
    'https://www.youtube.com/@tibees',

    # --- Gaming, streaming y ajedrez (2) ---
    'https://www.youtube.com/@WoshingoStreams',
    'https://www.youtube.com/@GothamChess',
    'https://www.youtube.com/@BaityBait',

    # --- Cultura, historia y videoensayo (37) ---
    'https://www.youtube.com/@Ter',
    'https://www.youtube.com/@ElConsejeronocturno',
    'https://www.youtube.com/@MIGALAD',
    'https://www.youtube.com/c/Caf%C3%A9Kyoto',
    'https://www.youtube.com/@semo_historia',
    'https://www.youtube.com/@DEMENTESMedia',
    'https://www.youtube.com/@FrancoPisso',
    'https://www.youtube.com/@witchcalli',
    'https://www.youtube.com/@viyaura',
    'https://www.youtube.com/@ArcadesBooks',
    'https://www.youtube.com/@DiegoRuzzarin',
    'https://www.youtube.com/@ManCarryingThing',
    'https://www.youtube.com/@98granos',
    'https://www.youtube.com/@RedditHistoriasSinFiltro',
    'https://www.youtube.com/@DrossRotzank',
    'https://www.youtube.com/@RicardoAlcaraz',
    'https://www.youtube.com/@RobPaperClips',
    'https://www.youtube.com/@RobPaperSheet',
    'https://www.youtube.com/@Pinwinsillo',
    'https://www.youtube.com/@atherion',
    'https://www.youtube.com/@ImpulsoSupremo333',
    'https://www.youtube.com/@noctivoyt',
    'https://www.youtube.com/@Unpocomejor1',
    'https://www.youtube.com/@elWacky2',
    'https://www.youtube.com/@Eze.martinez',
    'https://www.youtube.com/@CorduraArtificial',
    'https://www.youtube.com/@EsquizofreniaNatural',
    'https://www.youtube.com/@Monitorfantasma',
    'https://www.youtube.com/@dateunvlog',
    'https://www.youtube.com/@JaimeAltozano',
    'https://www.youtube.com/@VisualPolitik',
    'https://www.youtube.com/@CGPGrey',
    'https://www.youtube.com/@LEMMiNO',
    'https://www.youtube.com/@PolyMatter',
    'https://www.youtube.com/@ColdFusion',
    'https://www.youtube.com/@Nerdwriter1',
    'https://www.youtube.com/@Subterraneo',
    'https://www.youtube.com/@FoldingIdeas',
    'https://www.youtube.com/@JacobGeller',
    'https://www.youtube.com/@LindsayEllisVids',
    'https://www.youtube.com/@TheCinemaCartography',
    'https://www.youtube.com/@Nerdwriter',
    'https://www.youtube.com/@hbomberguy',
    'https://www.youtube.com/@cjthex',
    'https://www.youtube.com/@LikeStoriesofOld',
    'https://www.youtube.com/@PopCultureDetectiveAgency',
    'https://www.youtube.com/@ContraPoints',
    'https://www.youtube.com/@PhilosophyTube',
    'https://www.youtube.com/@PutoMikel',
    'https://www.youtube.com/@BeKindRewind',
    'https://www.youtube.com/@ZoomF7',
    'https://www.youtube.com/@KinoKarrete',
    'https://www.youtube.com/@patrickhwillems',
    'https://www.youtube.com/@JustWrite',
    'https://www.youtube.com/@NowYouSeeIt',
    'https://www.youtube.com/@CinemaStix',
    'https://www.youtube.com/@AccentedCinema',
    'https://www.youtube.com/@RoyalOceanFilmSociety',
    'https://www.youtube.com/@InPraiseofShadows',
    'https://www.youtube.com/@Sideways440',
    'https://www.youtube.com/@LaFilmotecaMaldita',
    'https://www.youtube.com/@AxlKss',
    'https://www.youtube.com/@DayoScript',
    'https://www.youtube.com/@PlanodeJuego',
    'https://www.youtube.com/@Nerdstalgic',
    'https://www.youtube.com/@Filmento',
    'https://www.youtube.com/@AdoreRodriguez',
    'https://www.youtube.com/@BlancaQuinonez',
    'https://www.youtube.com/@JordiMaquiavello',
    'https://www.youtube.com/@AntonioGarciaVillaran',
    'https://www.youtube.com/@Teloresumoasinomas',
    'https://www.youtube.com/@BobbyBroccoli',

    # --- Productividad, lifestyle y creadores (33) ---
    'https://www.youtube.com/@soycristinadayz',
    'https://www.youtube.com/@LatinoSueco',
    'https://www.youtube.com/@AliAbdaal',
    'https://www.youtube.com/@ThomasFrank',
    'https://www.youtube.com/@MattDAvella',
    'https://www.youtube.com/@NathanielDrew',
    'https://www.youtube.com/@LordDraugr',
    'https://www.youtube.com/@danielfelipemedina',
    'https://www.youtube.com/@paoalmontes',
    'https://www.youtube.com/@jefidos',
    'https://www.youtube.com/@judithtiral5713',
    'https://www.youtube.com/@NocheDeChicxs',
    'https://www.youtube.com/@DiegoRevueltaTV',
    'https://www.youtube.com/@lunamartinezoficial',
    'https://www.youtube.com/@DonebyLaura',
    'https://www.youtube.com/@irenesauriox',
    'https://www.youtube.com/@AleAbsolutable',
    'https://www.youtube.com/@Brinnn',
    'https://www.youtube.com/@Sambucha',
    'https://www.youtube.com/@ALXI_ESSAY',
    'https://www.youtube.com/@Landerdiazdelfresno',
    'https://www.youtube.com/@ELCACHONDO',
    'https://www.youtube.com/@bravogabobravo',
    'https://www.youtube.com/@FranqitoM',
    'https://www.youtube.com/@MisterKrax',
    'https://www.youtube.com/@vidamrr',
    'https://www.youtube.com/@KellyStamps',
    'https://www.youtube.com/@PlanetaJuan',
    'https://www.youtube.com/@clem',
    'https://www.youtube.com/@betterideas',
    'https://www.youtube.com/@ClaraCarmona',
    'https://www.youtube.com/@jessicafernandezgarcia',
    'https://www.youtube.com/@DonCanitro',
    'https://www.youtube.com/@LethalCrysis',

    # ============================================================
    # AMPLIACIÓN PREVIA
    # ============================================================
    # --- Negocios, emprendimiento y finanzas en español (15) ---
    'https://www.youtube.com/@ValueSchool',
    'https://www.youtube.com/@Rankia',
    'https://www.youtube.com/@Finect',
    'https://www.youtube.com/@JaviLinaresFinanzas',
    'https://www.youtube.com/@AcademiadeInversion',
    'https://www.youtube.com/@PabloGilTrader',
    'https://www.youtube.com/@HealthyPockets',
    'https://www.youtube.com/@NegociosTV',
    'https://www.youtube.com/@ElArteDeInvertir',
    'https://www.youtube.com/@JuanRamonRallo',
    'https://www.youtube.com/@MarcVidal',
    'https://www.youtube.com/@VilmaNunez',
    'https://www.youtube.com/@EndeavorMexico',
    'https://www.youtube.com/@ForbesMexico',
    'https://www.youtube.com/@ExpansionMx',

    # --- Negocios, startups y finanzas en inglés (16) ---
    'https://www.youtube.com/@GrahamStephan',
    'https://www.youtube.com/@MeetKevin',
    'https://www.youtube.com/@AndreiJikh',
    'https://www.youtube.com/@NateOBrien',
    'https://www.youtube.com/@ThePlainBagel',
    'https://www.youtube.com/@BenFelixCSI',
    'https://www.youtube.com/@PatrickBoyleOnFinance',
    'https://www.youtube.com/@TheSwedishInvestor',
    'https://www.youtube.com/@NewMoneyYouTube',
    'https://www.youtube.com/@MoneyGuyShow',
    'https://www.youtube.com/@DaveRamseyShow',
    'https://www.youtube.com/@CNBCMakeIt',
    'https://www.youtube.com/@CNBC',
    'https://www.youtube.com/@BloombergTV',
    'https://www.youtube.com/@YahooFinance',
    'https://www.youtube.com/@WSJ',

    # --- Tecnología, programación e IA en inglés (20) ---
    'https://www.youtube.com/@mkbhd',
    'https://www.youtube.com/@LinusTechTips',
    'https://www.youtube.com/@OpenAI',
    'https://www.youtube.com/@GoogleDevelopers',
    'https://www.youtube.com/@MicrosoftDeveloper',
    'https://www.youtube.com/@IBMTechnology',
    'https://www.youtube.com/@NVIDIADeveloper',
    'https://www.youtube.com/@AndrejKarpathy',
    'https://www.youtube.com/@lexfridman',
    'https://www.youtube.com/@YannicKilcher',
    'https://www.youtube.com/@aiadvantage',
    'https://www.youtube.com/@Fireship',
    'https://www.youtube.com/@freecodecamp',
    'https://www.youtube.com/@TraversyMedia',
    'https://www.youtube.com/@WebDevSimplified',
    'https://www.youtube.com/@TheCodingTrain',
    'https://www.youtube.com/@CoreyMS',
    'https://www.youtube.com/@sentdex',
    'https://www.youtube.com/@TechWithTim',
    'https://www.youtube.com/@CSDojo',

    # --- Tecnología y programación en español (14) ---
    'https://www.youtube.com/@BraisMoureDev',
    'https://www.youtube.com/@codigofacilito',
    'https://www.youtube.com/@VictorRoblesWEB',
    'https://www.youtube.com/@pildorasinformaticas',
    'https://www.youtube.com/@ProgramacionATS',
    'https://www.youtube.com/@CodigoMentor',
    'https://www.youtube.com/@jonmircha',
    'https://www.youtube.com/@manzdev',
    'https://www.youtube.com/@Suprapixel',
    'https://www.youtube.com/@Tecnonauta',
    'https://www.youtube.com/@ProAndroid',
    'https://www.youtube.com/@TopesDeGama',
    'https://www.youtube.com/@IsaMarcial',
    'https://www.youtube.com/@UrbanTecno',

    # --- Ciencia, educación y divulgación en inglés (16) ---
    'https://www.youtube.com/@TED',
    'https://www.youtube.com/@TEDxTalks',
    'https://www.youtube.com/@bigthink',
    'https://www.youtube.com/@WIRED',
    'https://www.youtube.com/@NationalGeographic',
    'https://www.youtube.com/@SciShow',
    'https://www.youtube.com/@SciShowSpace',
    'https://www.youtube.com/@TheSchoolOfLife',
    'https://www.youtube.com/@TheInfographicsShow',
    'https://www.youtube.com/@KhanAcademy',
    'https://www.youtube.com/@MITOpenCourseWare',
    'https://www.youtube.com/@StanfordOnline',
    'https://www.youtube.com/@Harvard',
    'https://www.youtube.com/@YaleCourses',
    'https://www.youtube.com/@OpenUniversity',
    'https://www.youtube.com/@WorldScienceFestival',

    # --- Ciencia, educación y divulgación en español (16) ---
    'https://www.youtube.com/@CuriosaMente',
    'https://www.youtube.com/@AcademiaPlay',
    'https://www.youtube.com/@PeroEsoEsOtraHistoria',
    'https://www.youtube.com/@MemoriasDePez',
    'https://www.youtube.com/@ElMapaDeSebas',
    'https://www.youtube.com/@ElCubilDePeter',
    'https://www.youtube.com/@Julioprofe',
    'https://www.youtube.com/@math2me',
    'https://www.youtube.com/@MatematicasProfeAlex',
    'https://www.youtube.com/@Profesor10demates',
    'https://www.youtube.com/@Educatina',
    'https://www.youtube.com/@unProfesor',
    'https://www.youtube.com/@SproutsEspanol',
    'https://www.youtube.com/@AprendemosJuntos2030',
    'https://www.youtube.com/@DWDocumental',
    'https://www.youtube.com/@BBCMundo',

    # --- Noticias, documentales y geopolítica en inglés (18) ---
    'https://www.youtube.com/@Vox',
    'https://www.youtube.com/@JohnnyHarris',
    'https://www.youtube.com/@RealLifeLore',
    'https://www.youtube.com/@HalfasInteresting',
    'https://www.youtube.com/@CaspianReport',
    'https://www.youtube.com/@TheB1M',
    'https://www.youtube.com/@Megaprojects',
    'https://www.youtube.com/@CompanyMan',
    'https://www.youtube.com/@EconomicsExplained',
    'https://www.youtube.com/@MoneyMacro',
    'https://www.youtube.com/@TLDRnews',
    'https://www.youtube.com/@TLDRnewsEU',
    'https://www.youtube.com/@BBCNews',
    'https://www.youtube.com/@CNN',
    'https://www.youtube.com/@MSNBC',
    'https://www.youtube.com/@ABCNews',
    'https://www.youtube.com/@CBSNews',
    'https://www.youtube.com/@NBCNews',

    # --- Noticias, documentales y análisis en español (15) ---
    'https://www.youtube.com/@elpais',
    'https://www.youtube.com/@ElMundo',
    'https://www.youtube.com/@LaVanguardia',
    'https://www.youtube.com/@DWNoticias',
    'https://www.youtube.com/@AJPlusEspanol',
    'https://www.youtube.com/@RTVE',
    'https://www.youtube.com/@ElUniversalMexico',
    'https://www.youtube.com/@AristeguiNoticias',
    'https://www.youtube.com/@LatinUS',
    'https://www.youtube.com/@AnimalPolitico',
    'https://www.youtube.com/@Nmas',
    'https://www.youtube.com/@lopezdoriga',
    'https://www.youtube.com/@AztecaNoticias',
    'https://www.youtube.com/@ImagenNoticias',
    'https://www.youtube.com/@ElHuffPost',

    # --- Música, kids, family, deportes y medios masivos (16) ---
    'https://www.youtube.com/@Tseries',
    'https://www.youtube.com/@SETIndia',
    'https://www.youtube.com/@Cocomelon',
    'https://www.youtube.com/@ElReinoInfantil',
    'https://www.youtube.com/@Pinkfong',
    'https://www.youtube.com/@LittleBabyBum',
    'https://www.youtube.com/@WWE',
    'https://www.youtube.com/@UFC',
    'https://www.youtube.com/@NBA',
    'https://www.youtube.com/@NFL',
    'https://www.youtube.com/@MLB',
    'https://www.youtube.com/@FIFA',
    'https://www.youtube.com/@Olympics',
    'https://www.youtube.com/@LaLiga',
    'https://www.youtube.com/@ESPN',
    'https://www.youtube.com/@ESPNDeportes',

    # --- Mega creadores y entretenimiento en inglés (17) ---
    'https://www.youtube.com/@MrBeast',
    'https://www.youtube.com/@PewDiePie',
    'https://www.youtube.com/@markiplier',
    'https://www.youtube.com/@jacksepticeye',
    'https://www.youtube.com/@DudePerfect',
    'https://www.youtube.com/@Smosh',
    'https://www.youtube.com/@GoodMythicalMorning',
    'https://www.youtube.com/@RyanTrahan',
    'https://www.youtube.com/@airrack',
    'https://www.youtube.com/@YesTheory',
    'https://www.youtube.com/@Casey',
    'https://www.youtube.com/@LoganPaulVlogs',
    'https://www.youtube.com/@JakePaul',
    'https://www.youtube.com/@KSI',
    'https://www.youtube.com/@Sidemen',
    'https://www.youtube.com/@TheTryGuys',
    'https://www.youtube.com/@SafiyaNygaard',

    # --- Mega creadores y entretenimiento en español (20) ---
    'https://www.youtube.com/@LuisitoComunica',
    'https://www.youtube.com/@werevertumorro',
    'https://www.youtube.com/@HolaSoyGerman',
    'https://www.youtube.com/@JuegaGerman',
    'https://www.youtube.com/@elrubiusOMG',
    'https://www.youtube.com/@auron',
    'https://www.youtube.com/@Vegetta777',
    'https://www.youtube.com/@Willyrex',
    'https://www.youtube.com/@TheGrefg',
    'https://www.youtube.com/@ibai',
    'https://www.youtube.com/@LuzuTV',
    'https://www.youtube.com/@enchufetv',
    'https://www.youtube.com/@Yuya',
    'https://www.youtube.com/@CaELiKe',
    'https://www.youtube.com/@AlexTienda',
    'https://www.youtube.com/@Alanxelmundo',
    'https://www.youtube.com/@LosPolinesios',
    'https://www.youtube.com/@JordiWild',
    'https://www.youtube.com/@TheWildProject',
    'https://www.youtube.com/@elescorpionsdorados',

    # --- Panorama amplio en español: cultura e internet (17) ---
    'https://www.youtube.com/@TriLine',
    'https://www.youtube.com/@DinosaurVlogs',
    'https://www.youtube.com/@DateUnShow',
    'https://www.youtube.com/@MatesMike',
    'https://www.youtube.com/@Robotitus',
    'https://www.youtube.com/@CienciaDeSofa',
    'https://www.youtube.com/@CulturaColectiva',
    'https://www.youtube.com/@Pictoline',
    'https://www.youtube.com/@Sopitas',
    'https://www.youtube.com/@ChumelTorres',
    'https://www.youtube.com/@LaJornada',
    'https://www.youtube.com/@Cinepolis',
    'https://www.youtube.com/@MauNieto',
    'https://www.youtube.com/@CarlosBallarta',
    'https://www.youtube.com/@MarthaDebayle',
    'https://www.youtube.com/@DimesYDiletes',
    'https://www.youtube.com/@SeRegalanDudas',

    # --- Cine, cultura, historia y storytelling en inglés (12) ---
    'https://www.youtube.com/@LessonsfromtheScreenplay',
    'https://www.youtube.com/@StudioBinder',
    'https://www.youtube.com/@EveryFrameaPainting',
    'https://www.youtube.com/@ThomasFlight',
    'https://www.youtube.com/@TheTake',
    'https://www.youtube.com/@WisecrackEDU',
    'https://www.youtube.com/@ScreenRant',
    'https://www.youtube.com/@CinemaSins',
    'https://www.youtube.com/@OverlySarcasticProductions',
    'https://www.youtube.com/@TheArmchairHistorian',
    'https://www.youtube.com/@KingsandGenerals',
    'https://www.youtube.com/@HistoryMatters',

    # --- Cine, cultura, historia y storytelling en español (11) ---
    'https://www.youtube.com/@TeLoResumo',
    'https://www.youtube.com/@CajaDePeliculas',
    'https://www.youtube.com/@ZEPfilms',
    'https://www.youtube.com/@SensacineTrailers',
    'https://www.youtube.com/@FueraDeFoco',
    'https://www.youtube.com/@AldoJones',
    'https://www.youtube.com/@LeyendasLegendarias',
    'https://www.youtube.com/@RelatosDeLaNoche',
    'https://www.youtube.com/@Nekojitablog',
    'https://www.youtube.com/@Nekojitablog2',
    'https://www.youtube.com/@ShaunTrack',

    # --- Comida, viajes y lifestyle en inglés (10) ---
    'https://www.youtube.com/@BestEverFoodReviewShow',
    'https://www.youtube.com/@MarkWiens',
    'https://www.youtube.com/@BingingwithBabish',
    'https://www.youtube.com/@bonappetit',
    'https://www.youtube.com/@JoshuaWeissman',
    'https://www.youtube.com/@AdamRagusea',
    'https://www.youtube.com/@Tasty',
    'https://www.youtube.com/@SortedFood',
    'https://www.youtube.com/@Eater',
    'https://www.youtube.com/@KaraandNate',

    # --- Comida, viajes y lifestyle en español (8) ---
    'https://www.youtube.com/@CocinaConCoqui',
    'https://www.youtube.com/@JaujaCocinaMexicana',
    'https://www.youtube.com/@CocinaParaTodos',
    'https://www.youtube.com/@LasRecetasDeMJ',
    'https://www.youtube.com/@RecetasdeEsbieta',
    'https://www.youtube.com/@GipsyChef',
    'https://www.youtube.com/@MarielDeViaje',
    'https://www.youtube.com/@Mundukos',

    # --- Salud, psicología y productividad (9) ---
    'https://www.youtube.com/@hubermanlab',
    'https://www.youtube.com/@DoctorMike',
    'https://www.youtube.com/@DrEricBergDC',
    'https://www.youtube.com/@HealthcareTriage',
    'https://www.youtube.com/@NutritionFactsOrg',
    'https://www.youtube.com/@Psych2go',
    'https://www.youtube.com/@TherapyinaNutshell',
    'https://www.youtube.com/@HealthyGamerGG',
    'https://www.youtube.com/@AndrewKirby',

    # ============================================================
    # NUEVA AMPLIACIÓN HASTA 650
    # ============================================================
    # --- Tecnología, IA y programación extra (18) ---
    'https://www.youtube.com/@Apple',
    'https://www.youtube.com/@Google',
    'https://www.youtube.com/@Microsoft',
    'https://www.youtube.com/@Meta',
    'https://www.youtube.com/@Tesla',
    'https://www.youtube.com/@AnthropicAI',
    'https://www.youtube.com/@GoogleDeepMind',
    'https://www.youtube.com/@AIExplainedOfficial',
    'https://www.youtube.com/@MatthewBerman',
    'https://www.youtube.com/@TheAIGRID',
    'https://www.youtube.com/@MattWolfe',
    'https://www.youtube.com/@AllAboutAI',
    'https://www.youtube.com/@NicolasSchurmann',
    'https://www.youtube.com/@SoyHenry',
    'https://www.youtube.com/@FalconMasters',
    'https://www.youtube.com/@Bluuweb',
    'https://www.youtube.com/@GentlemanProgramming',
    'https://www.youtube.com/@FreddyVega',

    # --- Noticias, geopolítica y medios (21) ---
    'https://www.youtube.com/@CBCNews',
    'https://www.youtube.com/@SkyNews',
    'https://www.youtube.com/@guardiannews',
    'https://www.youtube.com/@Reuters',
    'https://www.youtube.com/@AssociatedPress',
    'https://www.youtube.com/@AlJazeeraEnglish',
    'https://www.youtube.com/@FRANCE24English',
    'https://www.youtube.com/@DWNews',
    'https://www.youtube.com/@Firstpost',
    'https://www.youtube.com/@Channel4News',
    'https://www.youtube.com/@60minutes',
    'https://www.youtube.com/@VICE',
    'https://www.youtube.com/@PBSNewsHour',
    'https://www.youtube.com/@CNNenEspanol',
    'https://www.youtube.com/@Milenio',
    'https://www.youtube.com/@ElFinancieroBloomberg',
    'https://www.youtube.com/@MVSNoticias',
    'https://www.youtube.com/@SinEmbargoAlAire',
    'https://www.youtube.com/@revistaproceso',
    'https://www.youtube.com/@CanalOnceIPN',
    'https://www.youtube.com/@Canal22Mexico',

    # --- Documentales y conocimiento en inglés (15) ---
    'https://www.youtube.com/@BBCIdeas',
    'https://www.youtube.com/@TimelineChannel',
    'https://www.youtube.com/@HISTORY',
    'https://www.youtube.com/@SmithsonianChannel',
    'https://www.youtube.com/@CuriosityStream',
    'https://www.youtube.com/@DWDocumentary',
    'https://www.youtube.com/@BusinessInsider',
    'https://www.youtube.com/@InsiderScience',
    'https://www.youtube.com/@Seeker',
    'https://www.youtube.com/@besmart',
    'https://www.youtube.com/@MinuteEarth',
    'https://www.youtube.com/@animalwondersmontana',
    'https://www.youtube.com/@KOSMO_off',
    'https://www.youtube.com/@sea_space',
    'https://www.youtube.com/@melodysheep',

    # --- Streaming y gaming en inglés (24) ---
    'https://www.youtube.com/@xQcOW',
    'https://www.youtube.com/@Ludwig',
    'https://www.youtube.com/@Ninja',
    'https://www.youtube.com/@shroud',
    'https://www.youtube.com/@pokimane',
    'https://www.youtube.com/@AsmongoldTV',
    'https://www.youtube.com/@KaiCenatLive',
    'https://www.youtube.com/@IShowSpeed',
    'https://www.youtube.com/@AdinRoss',
    'https://www.youtube.com/@Sykkuno',
    'https://www.youtube.com/@Valkyrae',
    'https://www.youtube.com/@fuslie',
    'https://www.youtube.com/@QuarterJade',
    'https://www.youtube.com/@HasanAbi',
    'https://www.youtube.com/@OfflineTV',
    'https://www.youtube.com/@OTVandFriends',
    'https://www.youtube.com/@penguinz0',
    'https://www.youtube.com/@Northernlion',
    'https://www.youtube.com/@DougDoug',
    'https://www.youtube.com/@DisguisedToast',
    'https://www.youtube.com/@Sodapoppin',
    'https://www.youtube.com/@Mizkif',
    'https://www.youtube.com/@Jynxzi',
    'https://www.youtube.com/@CaseOhGames',

    # --- Streaming y gaming en español (25) ---
    'https://www.youtube.com/@IlloJuan',
    'https://www.youtube.com/@elxokas',
    'https://www.youtube.com/@JuanSGuarnizo',
    'https://www.youtube.com/@AriGameplays',
    'https://www.youtube.com/@riversgg',
    'https://www.youtube.com/@ElMariana',
    'https://www.youtube.com/@Roier',
    'https://www.youtube.com/@Quackity',
    'https://www.youtube.com/@QuackityToo',
    'https://www.youtube.com/@Komanche',
    'https://www.youtube.com/@Carola',
    'https://www.youtube.com/@Mayichi',
    'https://www.youtube.com/@spursito',
    'https://www.youtube.com/@Perxitaa',
    'https://www.youtube.com/@Cristinini',
    'https://www.youtube.com/@DJMaRiiO',
    'https://www.youtube.com/@knekro',
    'https://www.youtube.com/@TheGrefgLives',
    'https://www.youtube.com/@rubiusZ',
    'https://www.youtube.com/@elrubius',
    'https://www.youtube.com/@AuronPlay',
    'https://www.youtube.com/@IbaiLlanos',
    'https://www.youtube.com/@byViruZz',
    'https://www.youtube.com/@Mictia',
    'https://www.youtube.com/@Gemita',

    # --- Gaming histórico en inglés (23) ---
    'https://www.youtube.com/@DanTDM',
    'https://www.youtube.com/@VanossGaming',
    'https://www.youtube.com/@AliA',
    'https://www.youtube.com/@Technoblade',
    'https://www.youtube.com/@dream',
    'https://www.youtube.com/@GeorgeNotFound',
    'https://www.youtube.com/@Sapnap',
    'https://www.youtube.com/@TommyInnit',
    'https://www.youtube.com/@WilburPlays',
    'https://www.youtube.com/@LazarBeam',
    'https://www.youtube.com/@TypicalGamer',
    'https://www.youtube.com/@PrestonPlayz',
    'https://www.youtube.com/@Unspeakable',
    'https://www.youtube.com/@PopularMMOs',
    'https://www.youtube.com/@Aphmau',
    'https://www.youtube.com/@Kwebbelkop',
    'https://www.youtube.com/@H2ODelirious',
    'https://www.youtube.com/@CaptainSparklez',
    'https://www.youtube.com/@stampylonghead',
    'https://www.youtube.com/@MumboJumbo',
    'https://www.youtube.com/@Grian',
    'https://www.youtube.com/@SmallishBeans',
    'https://www.youtube.com/@ldshadowlady',

    # --- Gaming histórico en español (15) ---
    'https://www.youtube.com/@Mikecrack',
    'https://www.youtube.com/@invictor',
    'https://www.youtube.com/@elTrollino',
    'https://www.youtube.com/@Acenix',
    'https://www.youtube.com/@Bobicraft',
    'https://www.youtube.com/@Sparta356',
    'https://www.youtube.com/@MangelRogel',
    'https://www.youtube.com/@Fernanfloo',
    'https://www.youtube.com/@Folagor03',
    'https://www.youtube.com/@NexxuzHD',
    'https://www.youtube.com/@StaxxCraft',
    'https://www.youtube.com/@Lyna',
    'https://www.youtube.com/@KarimJuega',
    'https://www.youtube.com/@ElRichMC',
    'https://www.youtube.com/@TortillaLand',

    # --- Música global y LATAM (43) ---
    'https://www.youtube.com/@TaylorSwift',
    'https://www.youtube.com/@Beyonce',
    'https://www.youtube.com/@ArianaGrande',
    'https://www.youtube.com/@JustinBieber',
    'https://www.youtube.com/@eminemmusic',
    'https://www.youtube.com/@EdSheeran',
    'https://www.youtube.com/@BillieEilish',
    'https://www.youtube.com/@BadBunnyPR',
    'https://www.youtube.com/@KarolG',
    'https://www.youtube.com/@shakira',
    'https://www.youtube.com/@Jbalvin',
    'https://www.youtube.com/@Ozuna',
    'https://www.youtube.com/@Maluma',
    'https://www.youtube.com/@RauwAlejandroTv',
    'https://www.youtube.com/@ROSALIA',
    'https://www.youtube.com/@Bizarrap',
    'https://www.youtube.com/@dualipa',
    'https://www.youtube.com/@TheWeeknd',
    'https://www.youtube.com/@BrunoMars',
    'https://www.youtube.com/@DrakeOfficial',
    'https://www.youtube.com/@PostMalone',
    'https://www.youtube.com/@BLACKPINK',
    'https://www.youtube.com/@BANGTANTV',
    'https://www.youtube.com/@HYBELABELS',
    'https://www.youtube.com/@SMTOWN',
    'https://www.youtube.com/@JYPEntertainment',
    'https://www.youtube.com/@YGEntertainment',
    'https://www.youtube.com/@Rihanna',
    'https://www.youtube.com/@Maroon5',
    'https://www.youtube.com/@Coldplay',
    'https://www.youtube.com/@ImagineDragons',
    'https://www.youtube.com/@Metallica',
    'https://www.youtube.com/@Queen',
    'https://www.youtube.com/@LuisMiguel',
    'https://www.youtube.com/@AlejandroSanz',
    'https://www.youtube.com/@Camilo',
    'https://www.youtube.com/@Morat',
    'https://www.youtube.com/@Feid',
    'https://www.youtube.com/@GrupoFrontera',
    'https://www.youtube.com/@PesoPluma',
    'https://www.youtube.com/@ChristianNodal',
    'https://www.youtube.com/@NatanaelCano',
    'https://www.youtube.com/@LosAngelesAzules',

    # --- Infantil y familiar (33) ---
    'https://www.youtube.com/@VladandNiki',
    'https://www.youtube.com/@LikeNastyaofficial',
    'https://www.youtube.com/@RyansWorld',
    'https://www.youtube.com/@KidsDianaShow',
    'https://www.youtube.com/@DianaandRoma',
    'https://www.youtube.com/@ToysandColors',
    'https://www.youtube.com/@ChuChuTV',
    'https://www.youtube.com/@BouncePatrolKids',
    'https://www.youtube.com/@SuperSimpleSongs',
    'https://www.youtube.com/@BlueyOfficialChannel',
    'https://www.youtube.com/@PeppaPigOfficial',
    'https://www.youtube.com/@Blippi',
    'https://www.youtube.com/@MsRachel',
    'https://www.youtube.com/@SesameStreet',
    'https://www.youtube.com/@DisneyJunior',
    'https://www.youtube.com/@NickJr',
    'https://www.youtube.com/@CartoonNetwork',
    'https://www.youtube.com/@MashaBearEN',
    'https://www.youtube.com/@LooLooKids',
    'https://www.youtube.com/@LittleAngel',
    'https://www.youtube.com/@toycantando',
    'https://www.youtube.com/@elcanaldePlimPlim',
    'https://www.youtube.com/@GallinaPintadita',
    'https://www.youtube.com/@Cantajuego',
    'https://www.youtube.com/@Pocoyo',
    'https://www.youtube.com/@CanticosWorld',
    'https://www.youtube.com/@LuliPampin',
    'https://www.youtube.com/@SuperJoJoEspanol',
    'https://www.youtube.com/@LasRatitas',
    'https://www.youtube.com/@MashaOsoEspanol',
    'https://www.youtube.com/@DisneyJuniorLA',
    'https://www.youtube.com/@NickJrLA',
    'https://www.youtube.com/@PeppaPigEspanol',
    'https://www.youtube.com/@BlippiEspanol',
    'https://www.youtube.com/@BRIGHTSIDEOFFICIAL',
    'https://www.youtube.com/@5MinuteCraftsYouTube',

    # --- Deportes y eventos en vivo (7) ---
    'https://www.youtube.com/@KingsLeagueOfficial',
    'https://www.youtube.com/@KingsLeagueAmericas',
    'https://www.youtube.com/@elchiringuito',
    'https://www.youtube.com/@TUDN',
    'https://www.youtube.com/@FOXDeportes',
    'https://www.youtube.com/@DAZN',
    'https://www.youtube.com/@DAZNBoxing',

]

# Clasificación programática de la lista original del usuario.
ORIGINAL_CHANNEL_CATEGORIES = {
    'https://www.youtube.com/@MarianoTrejo': 'Finanzas, negocios y emprendimiento',
    'https://www.youtube.com/@la_inteligencia_artificial': 'Tecnología, IA y programación',
    'https://www.youtube.com/@humphrey': 'Tecnología, IA y programación',
    'https://www.youtube.com/@MisPropiasFinanzas': 'Finanzas, negocios y emprendimiento',
    'https://www.youtube.com/@AdriàSolàPastor': 'Finanzas, negocios y emprendimiento',
    'https://www.youtube.com/@EduardoRosas': 'Finanzas, negocios y emprendimiento',
    'https://www.youtube.com/@CésarDabiánFinanzas': 'Finanzas, negocios y emprendimiento',
    'https://www.youtube.com/@soycristinadayz': 'Productividad, lifestyle y creadores',
    'https://www.youtube.com/@MorisDieck': 'Finanzas, negocios y emprendimiento',
    'https://www.youtube.com/@AdrianSaenz': 'Finanzas, negocios y emprendimiento',
    'https://www.youtube.com/@FinanzasparatodosYT': 'Finanzas, negocios y emprendimiento',
    'https://www.youtube.com/@LuisMiNegocios': 'Finanzas, negocios y emprendimiento',
    'https://www.youtube.com/@AprendizFinanciero': 'Finanzas, negocios y emprendimiento',
    'https://www.youtube.com/@negociosyfinanzas2559': 'Finanzas, negocios y emprendimiento',
    'https://www.youtube.com/@pequenocerdocapitalista': 'Finanzas, negocios y emprendimiento',
    'https://www.youtube.com/@AlexHormozi': 'Finanzas, negocios y emprendimiento',
    'https://www.youtube.com/@CalebHammer': 'Finanzas, negocios y emprendimiento',
    'https://www.youtube.com/c/Myprimermillón': 'Finanzas, negocios y emprendimiento',
    'https://www.youtube.com/@starterstory': 'Finanzas, negocios y emprendimiento',
    'https://www.youtube.com/@irenealbacete': 'Finanzas, negocios y emprendimiento',
    'https://www.youtube.com/@bulkin_uri': 'Finanzas, negocios y emprendimiento',
    'https://www.youtube.com/@ExitoFinancieroOficial': 'Finanzas, negocios y emprendimiento',
    'https://www.youtube.com/@compuestospodcast': 'Finanzas, negocios y emprendimiento',
    'https://www.youtube.com/@JaimeHigueraEspanol': 'Finanzas, negocios y emprendimiento',
    'https://www.youtube.com/@jefillysh': 'Tecnología, IA y programación',
    'https://www.youtube.com/@EDteam': 'Tecnología, IA y programación',
    'https://www.youtube.com/@LatinoSueco': 'Productividad, lifestyle y creadores',
    'https://www.youtube.com/@Ter': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@doctorfision': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@EvaMariaBeristain': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@Unicoos': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@QuantumFracture': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@lagatadeschrodinger': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@CdeCiencia': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@elrobotdeplaton': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@PhysicsGirl': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@Veritasium': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@Vsauce': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@minutephysics': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@SmarterEveryDay': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@AsapSCIENCE': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@PBSSpaceTime': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@TheActionLab': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@numberphile': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@crashcourse': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@AliAbdaal': 'Productividad, lifestyle y creadores',
    'https://www.youtube.com/@ThomasFrank': 'Productividad, lifestyle y creadores',
    'https://www.youtube.com/@MattDAvella': 'Productividad, lifestyle y creadores',
    'https://www.youtube.com/@NathanielDrew': 'Productividad, lifestyle y creadores',
    'https://www.youtube.com/@LordDraugr': 'Productividad, lifestyle y creadores',
    'https://www.youtube.com/@danielfelipemedina': 'Productividad, lifestyle y creadores',
    'https://www.youtube.com/@omareducacionfinanciera': 'Finanzas, negocios y emprendimiento',
    'https://www.youtube.com/@TwoMinutePapers': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@ElConsejeronocturno': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@UnaFisicaSimplificada': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@gustavo-entrala': 'Finanzas, negocios y emprendimiento',
    'https://www.youtube.com/@ricardoalcados': 'Finanzas, negocios y emprendimiento',
    'https://www.youtube.com/@inversioninteligente_alain': 'Finanzas, negocios y emprendimiento',
    'https://www.youtube.com/@MIGALAD': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@paoalmontes': 'Productividad, lifestyle y creadores',
    'https://www.youtube.com/c/Caf%C3%A9Kyoto': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@watop_esp': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@jefidos': 'Productividad, lifestyle y creadores',
    'https://www.youtube.com/@judithtiral5713': 'Productividad, lifestyle y creadores',
    'https://www.youtube.com/@ProgramadorX': 'Tecnología, IA y programación',
    'https://www.youtube.com/@NocheDeChicxs': 'Productividad, lifestyle y creadores',
    'https://www.youtube.com/@Platzi': 'Tecnología, IA y programación',
    'https://www.youtube.com/@DiegoRevueltaTV': 'Productividad, lifestyle y creadores',
    'https://www.youtube.com/@lunamartinezoficial': 'Productividad, lifestyle y creadores',
    'https://www.youtube.com/@semo_historia': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@NateGentile7': 'Tecnología, IA y programación',
    'https://www.youtube.com/@DEMENTESMedia': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@FrancoPisso': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@witchcalli': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@viyaura': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@ArcadesBooks': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@DonebyLaura': 'Productividad, lifestyle y creadores',
    'https://www.youtube.com/@TwoCentsPBS': 'Finanzas, negocios y emprendimiento',
    'https://www.youtube.com/@bravosresearch': 'Finanzas, negocios y emprendimiento',
    'https://www.youtube.com/@ThatNateBlack': 'Finanzas, negocios y emprendimiento',
    'https://www.youtube.com/@DiegoRuzzarin': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@ManCarryingThing': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@comofuncionatunegocio': 'Finanzas, negocios y emprendimiento',
    'https://www.youtube.com/@irenesauriox': 'Productividad, lifestyle y creadores',
    'https://www.youtube.com/@98granos': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@WoshingoStreams': 'Gaming, streaming y ajedrez',
    'https://www.youtube.com/@midulive': 'Tecnología, IA y programación',
    'https://www.youtube.com/@AleAbsolutable': 'Productividad, lifestyle y creadores',
    'https://www.youtube.com/@RedditHistoriasSinFiltro': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@SantiagoAmatFinanzas': 'Finanzas, negocios y emprendimiento',
    'https://www.youtube.com/@Brinnn': 'Productividad, lifestyle y creadores',
    'https://www.youtube.com/@DrossRotzank': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@RicardoAlcaraz': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@RobPaperClips': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@RobPaperSheet': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@Pinwinsillo': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@atherion': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@ProfePiola': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@Sapienciapráctica': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@ImpulsoSupremo333': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@noctivoyt': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@Unpocomejor1': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@elWacky2': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@Sambucha': 'Productividad, lifestyle y creadores',
    'https://www.youtube.com/@thefinancialfreedomgirl': 'Finanzas, negocios y emprendimiento',
    'https://www.youtube.com/@ALXI_ESSAY': 'Productividad, lifestyle y creadores',
    'https://www.youtube.com/@Landerdiazdelfresno': 'Productividad, lifestyle y creadores',
    'https://www.youtube.com/@soydalto': 'Tecnología, IA y programación',
    'https://www.youtube.com/@ELCACHONDO': 'Productividad, lifestyle y creadores',
    'https://www.youtube.com/@bravogabobravo': 'Productividad, lifestyle y creadores',
    'https://www.youtube.com/@Eze.martinez': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@vidaprogramador': 'Tecnología, IA y programación',
    'https://www.youtube.com/@DotDager': 'Tecnología, IA y programación',
    'https://www.youtube.com/@elrincondeldev': 'Tecnología, IA y programación',
    'https://www.youtube.com/@mourede': 'Tecnología, IA y programación',
    'https://www.youtube.com/@FaztTech': 'Tecnología, IA y programación',
    'https://www.youtube.com/@bilinkis': 'Finanzas, negocios y emprendimiento',
    'https://www.youtube.com/@ELMAIKINIDEV': 'Tecnología, IA y programación',
    'https://www.youtube.com/@IA_Innova': 'Tecnología, IA y programación',
    'https://www.youtube.com/@WesRoth': 'Tecnología, IA y programación',
    'https://www.youtube.com/@RingaTech': 'Tecnología, IA y programación',
    'https://www.youtube.com/@alejavirivera': 'Tecnología, IA y programación',
    'https://www.youtube.com/@FranqitoM': 'Productividad, lifestyle y creadores',
    'https://www.youtube.com/@MisterKrax': 'Productividad, lifestyle y creadores',
    'https://www.youtube.com/@vidamrr': 'Productividad, lifestyle y creadores',
    'https://www.youtube.com/@EmprendeAprendiendo': 'Finanzas, negocios y emprendimiento',
    'https://www.youtube.com/@KellyStamps': 'Productividad, lifestyle y creadores',
    'https://www.youtube.com/@PlanetaJuan': 'Productividad, lifestyle y creadores',
    'https://www.youtube.com/@CorduraArtificial': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@EsquizofreniaNatural': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@Monitorfantasma': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@dateunvlog': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@clem': 'Productividad, lifestyle y creadores',
    'https://www.youtube.com/@betterideas': 'Productividad, lifestyle y creadores',
    'https://www.youtube.com/@jomakaze': 'Tecnología, IA y programación',
    'https://www.youtube.com/@KenJee_ds': 'Tecnología, IA y programación',
    'https://www.youtube.com/@HolaMundoDev': 'Tecnología, IA y programación',
    'https://www.youtube.com/@CreaYTransforma': 'Tecnología, IA y programación',
    'https://www.youtube.com/@TinaHuang1': 'Tecnología, IA y programación',
    'https://www.youtube.com/@ClaraCarmona': 'Productividad, lifestyle y creadores',
    'https://www.youtube.com/@jessicafernandezgarcia': 'Productividad, lifestyle y creadores',
    'https://www.youtube.com/@DonCanitro': 'Productividad, lifestyle y creadores',
    'https://www.youtube.com/@AI_In_Context': 'Tecnología, IA y programación',
    'https://www.youtube.com/@TheDiaryOfACEO': 'Finanzas, negocios y emprendimiento',
    'https://www.youtube.com/@GothamChess': 'Gaming, streaming y ajedrez',
    'https://www.youtube.com/@DotCSV': 'Tecnología, IA y programación',
    'https://www.youtube.com/@derivando': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@Antroporama': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@JaimeAltozano': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@LaHiperactina': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@VisualPolitik': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@kurzgesagt': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@MarkRober': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@TomScott': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@RealEngineering': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@Wendoverproductions': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@cleoabram': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@StuffMadeHere': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@sabinehossenfelder': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@3blue1brown': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@standupmaths': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@CGPGrey': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@LEMMiNO': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@PolyMatter': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@ColdFusion': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@Nerdwriter1': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@PracticalEngineeringChannel': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@domainofscience': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@BranchEducation': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@upandatom': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@NileRed': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@ScienceAsylum': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@acollierastro': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@eons': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@tibees': 'Ciencia, educación y divulgación',
    'https://www.youtube.com/@BobbyBroccoli': 'Cultura, historia y videoensayo',
    # Canales agregados desde lista de afinidad (2026-05-25)
    'https://www.youtube.com/@Subterraneo': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@FoldingIdeas': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@JacobGeller': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@LindsayEllisVids': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@TheCinemaCartography': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@Nerdwriter': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@hbomberguy': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@cjthex': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@LikeStoriesofOld': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@PopCultureDetectiveAgency': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@ContraPoints': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@PhilosophyTube': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@PutoMikel': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@BeKindRewind': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@ZoomF7': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@KinoKarrete': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@patrickhwillems': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@JustWrite': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@NowYouSeeIt': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@CinemaStix': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@AccentedCinema': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@RoyalOceanFilmSociety': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@InPraiseofShadows': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@Sideways440': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@LaFilmotecaMaldita': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@AxlKss': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@DayoScript': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@PlanodeJuego': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@BaityBait': 'Gaming, streaming y ajedrez',
    'https://www.youtube.com/@Nerdstalgic': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@Filmento': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@AdoreRodriguez': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@BlancaQuinonez': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@JordiMaquiavello': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@LethalCrysis': 'Productividad, lifestyle y creadores',
    'https://www.youtube.com/@AntonioGarciaVillaran': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@Teloresumoasinomas': 'Cultura, historia y videoensayo',
    'https://www.youtube.com/@BRIGHTSIDEOFFICIAL': 'Productividad, lifestyle y creadores',
    'https://www.youtube.com/@5MinuteCraftsYouTube': 'Productividad, lifestyle y creadores',
    'https://www.youtube.com/@KidsDianaShow': 'Infantil y familiar',
}

ORIGINAL_CHANNELS_COUNT = 176
PREVIOUS_ADDED_CHANNELS_COUNT = 250
NEW_ADDED_CHANNELS_COUNT = 264
TOTAL_CHANNELS_COUNT = 690

assert len(CHANNEL_URLS) == TOTAL_CHANNELS_COUNT
assert len(CHANNEL_URLS) == len(set(url.lower().rstrip("/") for url in CHANNEL_URLS))
